//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYSProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dersler()
        {
            this.OgrenciDersSecimTablosu = new HashSet<OgrenciDersSecimTablosu>();
        }
    
        public int DersID { get; set; }
        public string DersKodu { get; set; }
        public string DersAdı { get; set; }
        public string ZorunluMu { get; set; }
        public Nullable<int> Kredi { get; set; }
        public string Departman { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDersSecimTablosu> OgrenciDersSecimTablosu { get; set; }
    }
}
