//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYSProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.OgrenciDersSecimTablosu = new HashSet<OgrenciDersSecimTablosu>();
        }
    
        public int OgrenciID { get; set; }
        public string Isim { get; set; }
        public string Soyisim { get; set; }


        public string E_Mail { get; set; }
        public Nullable<int> AkademisyenID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        public virtual AkademisyenTablosu AkademisyenTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDersSecimTablosu> OgrenciDersSecimTablosu { get; set; }
    }
}
